#!/bin/bash                       
#PBS -P k96                       
#PBS -q express   
#PBS -l walltime=00:10:00         
#PBS -l ncpus=2                  
#PBS -l mem=7GB                  
#PBS -l jobfs=100GB               
#PBS -l wd                        
                                  
module unload openmpi/1.6.3       
module load openmpi/1.8.2
module load python3
python3 /short/k96/zls565/md/src/aimd.py
